### ISSUE TITLE
Version dependency of python3 and related packages

### ISSUE THREAD

**Issue by reduck96** [SUNCAT-Center/catmap#119]
Hi,

I installed python3(ver. 3.6.9) through source code compilation. And I installed packages
matplotlib 3.1.1
numpy 1.13.3
scipy 1.16.4
mpmath 1.1.0
ase 3.17.0
gmpy 1.17

However, I tried to run the example in this environment, it didn't work.

> tgmadmin@UOS-YOO` 3-refining_microkinetic_model]$ python3 mkm_job.py
> 
> Traceback (most recent call last):
>   File "mkm_job.py", line 1, in <module>
>     from catmap import ReactionModel
>   File "/TGM/Apps/PYTHON/3.6.9_for_CatMAP_20190718/lib/python3.6/site-packages/python_catmap-0.3.1-py3.6.egg/catmap/__init__.py", line 33, in <module>
>     from matplotlib.mlab import griddata as mlab_griddata
> ImportError: cannot import name 'griddata'

So I solved this "griddata call" problem by lowering the version of matplotlib (3.1.1 -> 2.2.4)
The example worked well and the results were good.

> [tgmadmin@UOS-YOO 3-refining_microkinetic_model]$ ls -al
> total 2372
> drwxr-xr-x  2 tgmadmin users     184 Jul 20 03:30 .
> drwxrwxrwt 28 root     root     4096 Jul 20 03:29 ..
> -rw-r--r--  1 tgmadmin users  342323 Jul 20 03:30 CO_oxidation.log
> -rw-r--r--  1 tgmadmin users    2503 Jul 18 12:53 CO_oxidation.mkm
> -rw-r--r--  1 tgmadmin users 1966805 Jul 20 03:30 CO_oxidation.pkl
> -rw-r--r--  1 tgmadmin users    5036 Jul 18 12:53 energies.txt
> -rw-r--r--  1 tgmadmin users   42650 Jul 20 03:30 FED.png
> -rw-r--r--  1 tgmadmin users    1462 Jul 18 13:41 mkm_job.py
> -rw-r--r--  1 tgmadmin users   36466 Jul 20 03:30 pretty_production_rate.pdf
> -rw-r--r--  1 tgmadmin users    8802 Jul 20 03:30 summary.tex

But, I tried to run CO_oxidation.log file as input in mkm_job.py but it did not work.

--- mkm_job.py file ---
from catmap import ReactionModel

#mkm_file = 'CO_oxidation.mkm'
mkm_file = 'CO_oxidation.log'
model = ReactionModel(setup_file=mkm_file)
...
--- mkm_job.py file done ---

> [tgmadmin@UOS-YOO 3-refining_microkinetic_model]$ python3 mkm_job.py
> Traceback (most recent call last):
>   File "mkm_job.py", line 5, in <module>
>     model = ReactionModel(setup_file=mkm_file)
>   File "/TGM/Apps/PYTHON/3.6.9_for_CatMAP_20190718/lib/python3.6/site-packages/python_catmap-0.3.1-py3.6.egg/catmap/model.py", line 125, in __init__
>     self.load(self.setup_file)
>   File "/TGM/Apps/PYTHON/3.6.9_for_CatMAP_20190718/lib/python3.6/site-packages/python_catmap-0.3.1-py3.6.egg/catmap/model.py", line 383, in load
>     exec(compile(open(setup_file, 'r').read(), '<string>', 'exec'), globs, locs)
>   File "<string>", line 22, in <module>
>   File "/TGM/Apps/PYTHON/3.6.9_for_CatMAP_20190718/lib/python3.6/codecs.py", line 321, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

It seems to be a version dependency of python3 and related packages used by catmap. I need help.
Thanks.

**Comment by gusmaogabriels** [comment]
Thanks @reduck96,

`griddata` has been deprecated in matplotlib. In the latest commit I have switched from matplotlib to scipy's (correlate)[https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.griddata.html].

It should be available upon reviewers validation.

Best,
Gabriel
