### ISSUE TITLE
CatMAP can't determine the self/cross-interaction parameters (Python 3.6)

### ISSUE THREAD

**Issue by efremowlad** [SUNCAT-Center/catmap#125]
I want Catmap to determine self/cross-interaction parameters from a set of coverage. 
In my energies.txt file I have  differential adsorption energies with corresponding coverage value. My parameters of the interaction model in *.mkm file:

_interaction_fitting_mode = ['numerical_differential']
numerical_delta_theta = 0.25
interaction_strength = 1.0
adsorbate_interaction_model = 'second_order'
interaction_response_function = 'smooth_piecewise_linear'_

When I run the code with Python 3.6, I have an error:
**"RuntimeError: dictionary changed size during iteration ".**

At the same time, this code works successfully with Python 2.7 (interaction parameters are well determined).

![2](https://user-images.githubusercontent.com/54527168/63736088-e4d3bf80-c8bc-11e9-8bc4-14ee39cdb665.JPG)

**Comment by gusmaogabriels** [comment]
This seems to have been fixed in the latter MR. Please reopen it if the issue still persists.
