### ISSUE TITLE
can't use catmap

### ISSUE THREAD

**Issue by shandongunivesity** [SUNCAT-Center/catmap#128]
Which one can give me an more complex example of input file of catmap?

Thank you very much

**Comment by gusmaogabriels** [comment]
Dear shandong, please visit the catmap read-the-docs [here](https://catmap.readthedocs.io/en/latest/) and consider the tutorials [here](https://github.com/SUNCAT-Center/catmap/tree/master/tutorials).

I hope these help.

Best,
