### ISSUE TITLE
Please Update Tutorial& TableParser._separator 

### ISSUE THREAD

**Issue by paptigshiyf** [SUNCAT-Center/catmap#131]
I‘m new to the catmap, and I try to run catmap with the input file in "Creating a Microkinetic Model". I just copy the "energies.txt" and "CO_oxidation.mkm" , but err occured:

  File "/~/catmap/parsers/table_parser.py", line 66, in parse
    raise ValueError('Required headers are missing! '+\
ValueError: Required headers are missing! Please be sure that all headers are specified: species_name surface_name site_name formation_energy frequencies reference

when I see the source code of  "table_parser.py", I see the code like:

self._separator = '\t'
headers = lines.pop(0).split(self._separator)
 L.split(self._separator, len(headers))

however, the energies.txt on the website subsitute "\t" with "    ". In fact, "string string".split() with no argument is enough, so please stop using split("\t") and use split() instead. I'm not sure if things are different in earlier python version for I have nerver used py2, but i think ... it really makes no sense

**Comment by gusmaogabriels** [comment]
HI @paptigshiyf , I have just run the tutorial file (`mkm_job.py`) without any issues: `catmap.__version__ = 0.3.1`, Python 3.8.1.
Can you provide additional information on your OS, exact python version, and the `.py` script in which you create the CatMAP model instance and run it?

Thanks

**Comment by paptigshiyf** [comment]
aha! thanks @gusmaogabriels ! Last time I didn't find the tutorial file ```mkm_job.py``` in the github repo，and instead I use the code and input on [catmap.readthedocs](https://catmap.readthedocs.io/en/latest/tutorials/creating_a_microkinetic_model.html). I just Ctrl+C and Ctrl+V all the code.  So the input file ```energiesWebsite.txt```, is like:
```
surface_name    site_name   species_name    formation_energy    bulk_structure  frequencies other_parameters    reference
None    gas CO2 2.45    None    [1333,2349,667,667] []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
None    gas CO  2.74    None    [2170]  []  "Energy Environ. Sci., 3, 1311-1315 (2010)"
None    gas O2  5.42    None    [1580]  []  "Falsig et al (2012)"
Ru  111 O   -0.07   fcc []  []  "Falsig et al (2012)"
Ni  111 O   0.35    fcc []  []  "Falsig et al (2012)"
Rh  111 O   0.55    fcc []  []  "Falsig et al (2012)"
Cu  111 O   1.07    fcc []  []  "Falsig et al (2012)"
Pd  111 O   1.55    fcc []  []  "Falsig et al (2012)"
Pt  111 O   1.62    fcc []  []  "Falsig et al (2012)"
Ag  111 O   2.05    fcc []  []  "Falsig et al (2012)"
Au  111 O   2.61    fcc []  []  "Falsig et al (2012)"
Ru  111 CO  1.3 fcc []  []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
Rh  111 CO  1.34    fcc []  []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
Pd  111 CO  1.55    fcc []  []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
Ni  111 CO  1.63    fcc []  []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
Pt  111 CO  1.7 fcc []  []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
Cu  111 CO  2.58    fcc []  []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
Ag  111 CO  2.99    fcc []  []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
Au  111 CO  3.04    fcc []  []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
Ru  111 O-CO    2.53    fcc []  []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
Rh  111 O-CO    3.1 fcc []  []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
Ni  111 O-CO    3.25    fcc []  []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
Pt  111 O-CO    4.04    fcc []  []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
Cu  111 O-CO    4.18    fcc []  []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
Pd  111 O-CO    4.2 fcc []  []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
Ag  111 O-CO    5.05    fcc []  []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
Au  111 O-CO    5.74    fcc []  []  "Angew. Chem. Int. Ed., 47, 4835 (2008)"
Ag  111 O-O 5.98    fcc []  []  "Falsig et al (2012)"
Au  111 O-O 7.22    fcc []  []  "Falsig et al (2012)"
Cu  111 O-O 4.74    fcc []  []  "Falsig et al (2012)"
Pt  111 O-O 5.35    fcc []  []  "Falsig et al (2012)"
Rh  111 O-O 3.79    fcc []  []  "Falsig et al (2012)"
Ru  111 O-O 3.34    fcc []  []  "Falsig et al (2012)"
Pd  111 O-O 5.34    fcc []  []  "Falsig et al (2012)"
```
Thanks for your reminder, I download ```energies.txt``` from the repo, and it's like:
```
surface_name	site_name	species_name	formation_energy	bulk_structure	frequencies	other_parameters	reference
None	gas	CO2	2.45	None	[1333,2349,667,667]	[]	"Angew. Chem. Int. Ed., 47, 4835 (2008)"
None	gas	CO	2.74	None	[2170]	[]	"Energy Environ. Sci., 3, 1311-1315 (2010)"
None	gas	O2	5.42	None	[1580]	[]	Falsig et al (2012)
Re	111	O	-1.15	fcc	[]	[]	Falsig et al (2012)
```
The minor difference is that the ```tabs``` or ```\t``` is turned to four ```space``` on [catmap.readthedocs](https://catmap.readthedocs.io/en/latest/tutorials/creating_a_microkinetic_model.html) by HTML5 or the explorer, so when I run the model 
Fine, it's done, the sily mistake is i haven't seen the tutorial file in the package.

**Comment by gusmaogabriels** [comment]
No problem! That’s great that you have found the source of the error.
