### ISSUE TITLE
How to calculate an integral_formation_energy?

### ISSUE THREAD

**Issue by KS-spec** [SUNCAT-Center/catmap#152]
Dear all,

Could you tell me how to calculate an integral_formation energy?
There is a colomn of integral_formation_enegy in a txt file of tutorial of second-order-interactions. I found an equation to get the energy(J. Am. Chem. Soc. 2016, 138, 11, 3705–3714), however I can't understand how to get some parameters in the equation. Is it possible to calculate with CATMAP?

thanks in advance

**Comment by ajmedford** [comment]
This refers to the integral heat of adsorption, which can be computed using DFT. The formula you refer to is the model used to model the integral formation energy as a continuous function of coverage, and assumes that the energy has been calculated with DFT at multiple coverages (then the parameters of the equation are fitted to the DFT results).

I do not remember the formula for calculating integral heat of adsorption off the top of my head, and don't want to make a mistake, so it is better if you can find it in the literature. Once calculated, it is possible to fit the equations using CatMAP, though I will warn that any model involving coverage dependence can be very challenging to parameterize or converge, so proceed with caution.

**Comment by KS-spec** [comment]
Thank you very much for your reply.

If it's possible, I would appreciate it if you could please tell me the literature with calculating integral heat of adsorption or the theoretical background of it.

**Comment by ajmedford** [comment]
You can find the formula at the bottom of page 14 of this paper: https://chemrxiv.org/engage/chemrxiv/article-details/60c74928337d6cba2fe276ab.

You may also wish to consult a textbook for a more conceptual explanation. I believe this is covered in Ch. 7 of "Concepts of Modern Catalysis and Kinetics" by Chorkendorff and Niemantsverdriet.

**Comment by KS-spec** [comment]
Thank you very much for your kind reply.
I’ll try to calculate it.
