### ISSUE TITLE
Create tutorial for custom gas species

### ISSUE THREAD

**Issue by ajmedford** [SUNCAT-Center/catmap#82]
We need a tutorial explaining how to add gas species that are not included in catmap/data/parameter_data.py. The tutorial should cover:

*How to add custom ideal gasses (e.g. creating a new entry in the atoms_dict property)
*How to add custom Shomate parameters using the "fit_shomate" function in catmap/thermodynamics/enthalpy_entropy.py
*How to verify the Shomate fit vs. the input data (see examples at end of enthalpy_entropy.py)
*When it is appropriate to submit Shomate data or ideal gas structure for inclusion in the source code of parameter_data.py

The last point is somewhat arbitrary, but I would say that we should only accept Shomate parameters that have been fit to well-established thermodynamic data (e.g. NIST or CRC). Ideal gas structures should probably be consistent with the ase.structure.molecule function (PBE geometries, I believe).

**Comment by chuanshi** [comment]
I'm on it!

**Comment by chuanshi** [comment]
#89
